### PR TITLE
python3 is required

### PR DESCRIPTION
**Pull request by beraldoleal**
I don't know if this pull is the best approach, but python3 is a dependency, right ? Also added the python3-lilv dependency instructions.

### CODE REVIEW

**Comment by falkTX** [comment]
The first one is fine, but not the 2nd.
Users shouldn't have to get the full kxstudio repos just for a simple python module.

**Comment by beraldoleal** [comment]
You are right. What do you prefer ? That I create another pull request ?

And about python3-lilv, once that this package is no more available on stable (only on old-stable repo), do you think that should be just mention it on README ? 

Thanks for the quick reply.

**Comment by falkTX** [comment]
Another pull request will be nice, thanks.

We should mention something about py3-lilv in the README yes.
tbh the entire README needs update.

**Comment by beraldoleal** [comment]
Thanks. I'm closing this pull request.
The first new one is in #32

**Pull request closed without merging**
